import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const BUILD={house:{name:'木屋',icon:'🏠',wood:22,stone:8,food:0},lumber:{name:'伐木场',icon:'🪵',wood:26,stone:8,food:0},quarry:{name:'采石场',icon:'🪨',wood:20,stone:12,food:0},farm:{name:'农田',icon:'🌾',wood:12,stone:0,food:0},barn:{name:'仓库',icon:'📦',wood:35,stone:18,food:0},mill:{name:'磨坊',icon:'🌬️',wood:42,stone:24,food:30},market:{name:'市场',icon:'⛺',wood:38,stone:16,food:20},blacksmith:{name:'铁匠铺',icon:'⚒️',wood:45,stone:35,food:0},school:{name:'学校',icon:'📚',wood:50,stone:30,food:0},clinic:{name:'诊所',icon:'⚕️',wood:48,stone:38,food:20},tavern:{name:'酒馆',icon:'🍺',wood:44,stone:20,food:25}};
let S={wood:180,stone:120,food:220,coin:250,iron:0,tool:6,pop:7,housing:8,happy:78,day:12,hour:10,season:0,year:1,speed:1,buildings:[]};
const scene=new THREE.Scene();scene.background=new THREE.Color(0x95b8c7);scene.fog=new THREE.FogExp2(0xa8c3c7,.008);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.className='gameCanvas';$('#game').prepend(renderer.domElement);
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,400);camera.position.set(52,44,58);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.47;controls.minDistance=20;controls.maxDistance=100;controls.mouseButtons={LEFT:THREE.MOUSE.PAN,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.ROTATE};
scene.add(new THREE.HemisphereLight(0xe8f5ff,0x415a34,2));const sun=new THREE.DirectionalLight(0xffefd2,4);sun.position.set(35,55,24);sun.castShadow=true;scene.add(sun);
const world=new THREE.Group();scene.add(world);const mat=(c)=>new THREE.MeshStandardMaterial({color:c,roughness:.9});
function M(g,m){const x=new THREE.Mesh(g,m);x.castShadow=true;x.receiveShadow=true;return x}
const ground=M(new THREE.PlaneGeometry(150,120),mat(0x6f9c50));ground.rotation.x=-Math.PI/2;world.add(ground);
const river=M(new THREE.PlaneGeometry(16,120),new THREE.MeshStandardMaterial({color:0x4b9fbe,roughness:.25,transparent:true,opacity:.92}));river.rotation.x=-Math.PI/2;river.position.set(-8,.08,0);world.add(river);
for(let i=0;i<120;i++){let x=(Math.random()-.5)*140,z=(Math.random()-.5)*108;if(Math.abs(x+8)<17||Math.hypot(x,z)<24){i--;continue}const g=new THREE.Group();const trunk=M(new THREE.CylinderGeometry(.3,.4,2.4,7),mat(0x6c472d));trunk.position.y=1.2;g.add(trunk);for(let j=0;j<3;j++){const c=M(new THREE.ConeGeometry(1.8-j*.2,2.8,8),mat(j%2?0x2f6138:0x3d7543));c.position.y=2.7+j*1.2;g.add(c)}g.position.set(x,0,z);world.add(g)}
function house(x,z,roof=0xa4513e,scale=1){const g=new THREE.Group();const b=M(new THREE.BoxGeometry(5.5,3.5,5),mat(0xc9b18d));b.position.y=1.75;g.add(b);const r=M(new THREE.ConeGeometry(4.2,2.4,4),mat(roof));r.position.y=4.55;r.rotation.y=Math.PI/4;r.scale.z=.82;g.add(r);const d=M(new THREE.BoxGeometry(1,2,.24),mat(0x5a402d));d.position.set(0,1.2,2.62);g.add(d);g.position.set(x,0,z);g.scale.setScalar(scale);world.add(g);return g}
function farm(x,z){const g=new THREE.Group();const s=M(new THREE.BoxGeometry(8,.22,6),mat(0x7c5936));s.position.y=.1;g.add(s);for(let a=-3;a<=3;a+=.75)for(let b=-2;b<=2;b+=.75){const c=M(new THREE.ConeGeometry(.13,.7,5),mat(0xc6a53e));c.position.set(a,.45,b);g.add(c)}g.position.set(x,0,z);world.add(g)}
function mill(x,z){const g=house(x,z,0x8b543d,1.05);const blades=new THREE.Group();for(let i=0;i<4;i++){const b=M(new THREE.BoxGeometry(.45,5.5,.2),mat(0xb8996a));b.position.y=2.7;b.rotation.z=i*Math.PI/2;blades.add(b)}blades.position.set(0,4.5,3);blades.name='blades';g.add(blades);return g}
const roads=[[[-24,-6],[26,-6]],[[-8,-24],[-8,24]]];for(const [a,b] of roads){const dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz),r=M(new THREE.BoxGeometry(2,.08,len),mat(0xaa9063));r.position.set((a[0]+b[0])/2,.05,(a[1]+b[1])/2);r.rotation.y=Math.atan2(dx,dz);world.add(r)}
for(let z=-5;z<=5;z+=1.4){const p=M(new THREE.BoxGeometry(17,.35,1),mat(0x745035));p.position.set(-8,.7,z);world.add(p)}
house(-20,-5);house(-12,-2,0xb05b43);house(4,-4,0x355f86,1.15);house(16,-2,0x8b5b3d,1.1);farm(-2,11);farm(8,12);mill(17,11);house(-18,14,0x6d774c,1.1);
const villagers=[];for(let i=0;i<S.pop;i++){const g=new THREE.Group();const body=M(new THREE.CapsuleGeometry(.3,.75,4,8),mat([0x5278a8,0x9c5d4e,0x5e855e,0x7a5b8d][i%4]));body.position.y=.8;g.add(body);const h=M(new THREE.SphereGeometry(.3,10,8),mat(0xd9ad86));h.position.y=1.55;g.add(h);g.userData={a:Math.random()*Math.PI*2,r:7+Math.random()*15,s:.2+Math.random()*.15};world.add(g);villagers.push(g)}
function hud(){const set=(id,v)=>{const e=$('#'+id);if(e)e.textContent=v};set('wood',Math.floor(S.wood));set('stone',Math.floor(S.stone));set('food',Math.floor(S.food));set('coin',Math.floor(S.coin));set('iron',Math.floor(S.iron));set('tool',Math.floor(S.tool));set('pop',S.pop+'/'+S.housing);set('happy',S.happy+'%');set('date',['春季','夏季','秋季','冬季'][S.season]+' '+S.day+'日 · Year '+S.year);set('time',String(S.hour).padStart(2,'0')+':00')}
function dock(){$('#buildDock').innerHTML=Object.entries(BUILD).map(([k,d])=>'<button class="buildBtn" data-build="'+k+'"><i>'+d.icon+'</i><span>'+d.name+'</span></button>').join('');$$('[data-build]').forEach(b=>b.addEventListener('click',()=>{const d=BUILD[b.dataset.build];if(S.wood<d.wood||S.stone<d.stone||S.food<d.food)return toast('资源不足');S.wood-=d.wood;S.stone-=d.stone;S.food-=d.food;toast('已规划 '+d.name+'，完整自由建造系统正在接入');hud()}))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1700)}
$$('.speedBtns button').forEach(b=>b.addEventListener('click',()=>{$$('.speedBtns button').forEach(x=>x.classList.remove('on'));b.classList.add('on');S.speed=+b.dataset.s}));
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();dock();hud();
let last=performance.now(),acc=0;function loop(now){requestAnimationFrame(loop);const dt=Math.min(.06,(now-last)/1000);last=now;acc+=dt*S.speed;if(acc>1.1){acc=0;S.hour++;if(S.hour>=24){S.hour=0;S.day++;S.food=Math.max(0,S.food-S.pop*1.5)}hud()}for(const v of villagers){v.userData.a+=dt*v.userData.s*S.speed;v.position.set(Math.cos(v.userData.a)*v.userData.r*.8,0,Math.sin(v.userData.a)*v.userData.r*.55);v.rotation.y=-v.userData.a+Math.PI/2}world.traverse(o=>{if(o.name==='blades')o.rotation.z+=dt*.6*S.speed});controls.update();renderer.render(scene,camera)}requestAnimationFrame(loop);setTimeout(()=>$('#loading').classList.add('hide'),700);